### ISSUE TITLE
Possibly mistake on docs?

### ISSUE THREAD

**Issue by r-martins** [markshust/magento2-module-simpledata#11]
I was following the docs scrictly (I reckon) and wasn't able to create a block.
Finally I realized the docs led me to create the patch file under <module>/Data/Setup/Patch/Data/MyClass.php.

But it only works if I create under <module/Setup/Patch/Data/MyClass.php.

Maybe I missed some other point here, but...

**Comment by markshust** [comment]
Yes, the first examples for creating, updating, & deleting blocks use setup patch data scripts, so they would need to be at the `Setup/Patch/Data` location. That said, there are also examples of using these simple methods with dependency injection at https://github.com/markshust/magento2-module-simpledata#example-using-dependency-injection

**Comment by r-martins** [comment]
Just to make it clear, the problem I pointed was an extra /Data/ in the docs. Not the fact of it was using the old Setup-way of doing things.
Never mind.. maybe I did some confusion, but sorted that out anyway.

**Comment by markshust** [comment]
Ah ok, no worrries! "data" setup patch scripts typically go in a `Setup/Patch/Data` directory... but I can see how that can be confused with the name of this module being `Data`. I should have picked a better name! 😅
