### ISSUE TITLE
What is the purpose of this extension?

### ISSUE THREAD

**Issue by Eddcapone** [markshust/magento2-module-simpledata#3]
I try to figure out what this extension does? Whats the goal, to which persons is this extension aimed? What problems does it solve?

**Comment by markshust** [comment]
See Summary https://github.com/markshust/magento2-module-simpledata#summary

**Comment by Eddcapone** [comment]
I already saw it, but it does not really explain anything in detail. Not sure how this extension gives any benefit, when do I need it.

**Comment by markshust** [comment]
> For example, here is a data patch script to update the content of a CMS page with and without SimpleData:

![demo](https://user-images.githubusercontent.com/437029/91343421-87fa3600-e7aa-11ea-9b72-e3f28886f6cf.png)

It's quite simple really. Without SimpleData, your data patch scripts look like the left. With it, it looks like the right.
